// import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import MainContent from "./MainContent";
import Providers from "./Providers";
import Script from "next/script";

export const metadata = {
  title: 'Mel Portfolio',
  description: 'portfolio',
};

export default function RootLayout() {
  return (
    <html lang="en">
      <head>
        <title>Melanie Casasco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="shortcut icon" href="/favicon.ico" />
        
        {/* Google Analytics */}
          <Script
            src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
            strategy="afterInteractive"
          />
          <Script id="google-analytics" strategy="afterInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-2MPGVF45HG', {
                page_path: window.location.pathname,
              });
            `}
          </Script>
      </head>
      <body>
        <Providers>
          <MainContent />
        </Providers>
      </body>
    </html>
  );
}
