import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import MainContent from "./MainContent";
import Providers from "./Providers";

/* const metadata: Metadata = {
  title: "Mel Portfolio",
  description: "Generated by create next app",
}; */

export default function RootLayout() {
  return (
    <html lang="en">
      <head>
        <title>Melanie Casasco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </head>
      <body>
        <Providers>
          <MainContent />
        </Providers>
      </body>
    </html>
  );
}
