import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import MainContent from "./MainContent";
import Providers from "./Providers";
import Script from "next/script";
import GoogleAnalytics from "./GoogleAnalytics";

export const metadata = {
  title: 'Mel Portfolio',
  description: 'portfolio',
};

export default function RootLayout() {
  return (
    <html lang="en">
      <head>
        <title>Melanie Casasco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="shortcut icon" href="/favicon.ico" />
        
        {/* Google Analytics */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-BFEGKVJSZ9"
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-BFEGKVJSZ9', {
                page_title: document.title,
                page_location: window.location.href
              });
            `,
          }}
        />
      </head>
      <body>
        <GoogleAnalytics />
        <Providers>
          <MainContent />
        </Providers>
      </body>
    </html>
  );
}
